# Generated by Django 4.2.4 on 2023-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
